In [2]:
import numpy as np

What is NumPy?
NumPy is a Python library used for working with arrays.

Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

In [5]:
# Create a NumPy array:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
#A dimension in arrays is one level of array depth (nested arrays).
#nested array: are arrays that have arrays as their elements.
#NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

"""0D array with value 42"""
arr = np.array(42)
print(arr)
print(arr.ndim)
print('-'*20)

"""1D array"""
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.ndim)
print('-'*20)

"""2D array"""
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.ndim)
print('-'*20)

"""3D array"""
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)
print(arr.ndim)
print('-'*20)



42
0
--------------------
[1 2 3 4 5]
1
--------------------
[[1 2 3]
 [4 5 6]]
2
--------------------
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3
--------------------


In [7]:
#An array can have any number of dimensions.
#When the array is created, you can define the number of dimensions by using the ndmin argument.

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)



[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [15]:
""" Access Array Elements
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.
"""

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr, "\n", "-"*20)
print(arr[0, 1, 2])


arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr[1, -1])

2nd element on 1st row:  2
5th element on 2nd row:  10
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 
 --------------------
6
Last element from 2nd dim:  10


In [24]:
"""Slicing arrays
Slicing in python means taking elements from one given index to another given index.
"""
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

#Note: The result includes the start index, but excludes the end index.

print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2], type(arr[1:5:2]))
print(arr[::2])

print("-"*20)

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

#From the second element, slice elements from index 1 to index 4 (not included):
print(arr[1, 1:4])

#From both elements, return index 2:
print(arr[:, 2])
print(arr[0:2, 2])

#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:
print(arr[0:2, 1:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4] <class 'numpy.ndarray'>
[1 3 5 7]
--------------------
[7 8 9]
[3 8]
[3 8]
[[2 3 4]
 [7 8 9]]


In [30]:
"""Checking the Data Type of an Array
The NumPy array object has a property called dtype that returns the data type of the array
"""

arr = np.array([1, 2, 3, 4])
print(arr.dtype)

arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

"""Creating Arrays With a Defined Data Type"""
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

"""Creating an array with data type 4 bytes integer:"""
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr, arr.dtype)

int32
<U6
[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4] int32


In [31]:
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [32]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32
[ True False  True]
bool


In [34]:
"""Make a copy, change the original array, and display both arrays"""

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

"""Make a view, change the original array, and display both arrays"""

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]


In [3]:
"""Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?
Every NumPy array has the attribute base that returns None if the array owns the data.
Otherwise, the base  attribute refers to the original object."""

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [39]:
"""Shape of an Array
The shape of an array is the number of elements in each dimension.
"""

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr, '\n', arr.shape)

print('-'*20)

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('shape of array :', arr.shape)

[[1 2 3 4]
 [5 6 7 8]] 
 (2, 4)
--------------------
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [47]:
"""Reshaping arrays
Reshaping means changing the shape of an array.
The shape of an array is the number of elements in each dimension.
By reshaping we can add or remove dimensions or change number of elements in each dimension
"""

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

#Reshape From 1-D to 2-D
newarr = arr.reshape(4, 3)
print(newarr, '\n', '-'*20)

#Reshape From 1-D to 3-D
newarr = arr.reshape(2, 3, 2)
print(newarr, '\n', '-'*20)

"""Unknown Dimension
You are allowed to have one "unknown" dimension.
Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.
Pass -1 as the value, and NumPy will calculate this number for you
Note: We can not pass -1 to more than one dimension.
"""

newarr = arr.reshape(2, 2, -1) # '-1' é determinado como '3'
print(newarr)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 
 --------------------
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] 
 --------------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [55]:
"""Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.
We can use reshape(-1) to do this
"""

arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)


"""Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy."""

[1 2 3 4 5 6]


'Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy'

In [60]:
"""Iterating Arrays"""

#Iterate on the elements of the following 2-D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)
print('-'*20)

#To return the actual values, the scalars, we have to iterate the arrays in each dimension.

for x in arr:
  for y in x:
    for z in y:
      print(z)
print('-'*20)

"""Iterating Arrays Using nditer()"""
for x in np.nditer(arr):
  print(x)
print('-'*20)

#Iterating With Different Step Size
for x in np.nditer(arr[:, ::2]): #Todas as linhas e o intervalo inteiro de 2 em 2
  print(x)
print('-'*20)


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
--------------------
1
2
3
4
5
6
7
8
9
10
11
12
--------------------
1
2
3
4
5
6
7
8
9
10
11
12
--------------------
1
2
3
7
8
9
--------------------


In [61]:
#Enumerated Iteration Using ndenumerate()
for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


No NumPy, o termo **"axis"** refere-se às direções (ou eixos) ao longo das quais as operações são realizadas em um array multidimensional. Imagine um array como uma estrutura com várias "camadas", e cada eixo representa uma dessas direções.

Aqui vai uma analogia para entender melhor:

1. **Eixo 0 (axis=0): o eixo das "linhas" (de cima para baixo)**.
   - Imagine uma tabela com linhas e colunas. O eixo 0 se refere às **linhas** — ele se move de cima para baixo.
   - Por exemplo, ao somar um array ao longo do eixo 0 (`np.sum(array, axis=0)`), você está somando valores **em cada coluna**.

2. **Eixo 1 (axis=1): o eixo das "colunas" (da esquerda para a direita)**.
   - Este é o eixo das **colunas** — ele se move da esquerda para a direita.
   - Ao somar ao longo do eixo 1 (`np.sum(array, axis=1)`), você está somando valores **em cada linha**.

Para uma intuição visual:

   - Imagine um array 2D como uma tabela de linhas e colunas:
     ```
     [[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]
     ```

   - `np.sum(array, axis=0)` resulta na soma ao longo das colunas (de cima para baixo):
     ```
     [1+4+7, 2+5+8, 3+6+9] = [12, 15, 18]
     ```

   - `np.sum(array, axis=1)` resulta na soma ao longo das linhas (da esquerda para a direita):
     ```
     [1+2+3, 4+5+6, 7+8+9] = [6, 15, 24]
     ```

Para arrays de dimensões maiores, os eixos seguem essa mesma lógica.

In [70]:
"""Joining NumPy Arrays
Joining means putting contents of two or more arrays in a single array.
We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0."""

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr, '\n', '-'*20)

#Join two 2-D arrays along rows (axis=1):
arr1 = np.array([[1, 2], [3, 4]])
print(arr1,'\n', '-'*20)
arr2 = np.array([[5, 6], [7, 8]])
print(arr2,'\n', '-'*20)

arr = np.concatenate((arr1, arr2), axis=1)
print(arr, '\n', arr.shape ,'\n', '-'*20)

arr = np.concatenate((arr1, arr2), axis=0)
print(arr, '\n', arr.shape ,'\n', '-'*20)




[1 2 3 4 5 6] 
 --------------------
[[1 2]
 [3 4]] 
 --------------------
[[5 6]
 [7 8]] 
 --------------------
[[1 2 5 6]
 [3 4 7 8]] 
 (2, 4) 
 --------------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]] 
 (4, 2) 
 --------------------


In [76]:
"""Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.
We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0."""

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
print(arr, '\n', arr.shape ,'\n', '-'*20)

arr = np.stack((arr1, arr2), axis=0)
print(arr, '\n', arr.shape ,'\n', '-'*20)

#hstack() to stack along rows (o mesmo que o concatenate ou o reshape(-1))
arr = np.hstack((arr1, arr2))
print(arr, '\n', arr.shape ,'\n', '-'*20)

arr = np.vstack((arr1, arr2))
print(arr, '\n', arr.shape ,'\n', '-'*20)

arr = np.dstack((arr1, arr2))
print(arr, '\n', arr.shape ,'\n', '-'*20)


[[1 4]
 [2 5]
 [3 6]] 
 (3, 2) 
 --------------------
[[1 2 3]
 [4 5 6]] 
 (2, 3) 
 --------------------
[1 2 3 4 5 6] 
 (6,) 
 --------------------
[[1 2 3]
 [4 5 6]] 
 (2, 3) 
 --------------------
[[[1 4]
  [2 5]
  [3 6]]] 
 (1, 3, 2) 
 --------------------


In [80]:
"""Split Into Arrays
The return value of the array_split() method is an array containing each of the split as an array.
If you split an array into 3 arrays, you can access them from the result just like any array element"""

def exibe(newarr):
    for x in newarr:
        print(x, x.shape, '\n')
    print('-'*20)

#Split the 2-D array into three 2-D arrays.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)
exibe(newarr)
	
#Split the 2-D array into three 2-D arrays along rows.
newarr = np.array_split(arr, 3, axis=1)
exibe(newarr)

[[1 2 3]
 [4 5 6]] (2, 3) 

[[ 7  8  9]
 [10 11 12]] (2, 3) 

[[13 14 15]
 [16 17 18]] (2, 3) 

--------------------
[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]] (6, 1) 

[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]] (6, 1) 

[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]] (6, 1) 

--------------------


In [85]:
"""Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.
To search an array, use the where() method."""

#The example will return a tuple: (array([3, 5, 6],). Which means that the value 4 is present at index 3, 5, and 6.
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

#Find the indexes where the values are even:
x = np.where(arr%2 == 0)
print(x)


"""Search Sorted
There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.
Note: The searchsorted() method is assumed to be used on sorted arrays."""

#The number 7 should be inserted on index 1 to remain the sort order.
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

#The number 7 should be inserted on index 2 to remain the sort order.
x = np.searchsorted(arr, 7, side='right') #Find the indexes where the value 7 should be inserted, starting from the right
print(x)

#Find the indexes where the values 2, 4, and 6 should be inserted:
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)
#The return value is an array: [1 2 3] containing the three indexes where 2, 4, 6 would be inserted in the original array to maintain the order.



(array([3, 5, 6], dtype=int64),)
(array([1, 3, 5, 6], dtype=int64),)
1
2
[1 2 3]


In [87]:
"""Sorting Arrays
Sorting means putting elements in an ordered sequence.
Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.
The NumPy ndarray object has a function called sort(), that will sort a specified array."""

arr = np.array([3, 2, 0, 1])
print(np.sort(arr), '\n')

#If you use the sort() method on a 2-D array, both arrays will be sorted:
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[0 1 2 3] 

[[2 3 4]
 [0 1 5]]


In [89]:
"""Filtering Arrays
Getting some elements out of an existing array and creating a new array out of them is called filtering.
In NumPy, you filter an array using a boolean index list (máscara booleana)."""

#Create a filter array that will return only values higher than 42:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)


#Create a filter array that will return only even elements from the original array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)


[False False  True  True]
[43 44]
[False  True False  True False  True False]
[2 4 6]
