In [3]:
import numpy as np

In [6]:
#Create your own ufunc (universal function) for addition:

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

#Check if a function is a ufunc:
print(type(np.add))

print(type(np.concatenate))


[6 8 10 12]
<class 'numpy.ufunc'>
<class 'numpy._ArrayFunctionDispatcher'>


In [9]:
"""Simple Arithmetic
You could use arithmetic operators + - * / directly between NumPy arrays, but this section discusses an extension of the same where we have functions that can take any array-like objects e.g. lists, tuples etc. and perform arithmetic conditionally.

Arithmetic Conditionally: means that we can define conditions where the arithmetic operation should happen.

All of the discussed arithmetic functions take a where parameter in which we can specify that condition."""


#The add() function sums the content of two arrays, and return the results in a new array.

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)
print(newarr)

#The subtract() function subtracts the values from one array with the values from another array, and return the results in a new array.

newarr = np.subtract(arr1, arr2)
print(newarr)


#The multiply() function multiplies the values from one array with the values from another array, and return the results in a new array.

newarr = np.multiply(arr1, arr2)
print(newarr)

#The divide() function divides the values from one array with the values from another array, and return the results in a new array.

newarr = np.divide(arr1, arr2)
print(newarr)

#The power() function rises the values from the first array to the power of the values of the second array, and return the results in a new array.

newarr = np.power(arr1, arr2)
print(newarr)

#Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.

newarr = np.mod(arr1, arr2)
print(newarr)
newarr = np.remainder(arr1, arr2)
print(newarr)

#The divmod() function return both the quotient and the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.

newarr = np.divmod(arr1, arr2)
print(newarr)

#Both the absolute() and the abs() functions do the same absolute operation element-wise but we should use absolute() to avoid confusion with python's inbuilt math.abs()

arr = np.array([-1, -2, 1, 2, 3, -4])
newarr = np.absolute(arr)
print(newarr)



[30 32 34 36 38 40]
[-10 -10 -10 -10 -10 -10]
[200 231 264 299 336 375]
[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6       ]
[ 1661992960   602408795           0  1487897765  1090519040 -1144744561]
[10 11 12 13 14 15]
[10 11 12 13 14 15]
(array([0, 0, 0, 0, 0, 0]), array([10, 11, 12, 13, 14, 15]))
[1 2 1 2 3 4]


In [24]:
from math import log
"""Rounding Decimals
There are primarily five ways of rounding off decimals in NumPy:

truncation
fix
rounding
floor
ceil"""

#Truncation: Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.
arr = np.trunc([-3.1666, 3.6667])
print(arr)
arr = np.fix([-3.1666, 3.6667])
print(arr)
print('\n','-'*20)


#The around() function increments preceding digit or decimal by 1 if >=5 else do nothing. E.g. round off to 1 decimal point, 3.16666 is 3.2
arr = np.around(3.1666, 2)
print(arr)
print('\n','-'*20)


#The floor() function rounds off decimal to nearest lower integer. E.g. floor of 3.166 is 3.
arr = np.floor([-3.1666, 3.6667])
print(arr)
print('\n','-'*20)


#The ceil() function rounds off decimal to nearest upper integer.E.g. ceil of 3.166 is 4.
arr = np.ceil([-3.1666, 3.6667])
print(arr)
print('\n','-'*20)


#Use the log2() function to perform log at the base 2.
arr = np.arange(1, 10)
print(np.log2(arr))
print('\n','-'*20)


#Use the log10() function to perform log at the base 10.
print(np.log10(arr))
print('\n','-'*20)


#Use the log() function to perform log at the base e.
print(np.log(arr))
print('\n','-'*20)


#Log at Any Base
nplog = np.frompyfunc(log, 2, 1)
print(nplog(100, 15))
print('\n','-'*20)


#Find the LCM (Lowest Common Multiple) of all values of an array where the array contains all integers from 1 to 10:
arr = np.array([3, 6, 9])
x = np.lcm.reduce(arr)
print(x)
print('\n','-'*20)
#The reduce() method will use the ufunc, in this case the lcm() function, on each element, and reduce the array by one dimension.


#Find the GCD (Greatest Common Denominator) for all of the numbers in the following array:
arr = np.array([20, 8, 32, 36, 16])
x = np.gcd.reduce(arr)
print(x)
print('\n','-'*20)


[-3.  3.]
[-3.  3.]

 --------------------
3.17

 --------------------
[-4.  3.]

 --------------------
[-3.  4.]

 --------------------
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]

 --------------------
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]

 --------------------
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]

 --------------------
1.7005483074552052

 --------------------
18

 --------------------


In [16]:
#Summations

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)
print(newarr)

#Sum the values in arr1 and the values in arr2:
newarr = np.sum([arr1, arr2])
print(newarr)

newarr = np.sum([arr1, arr2], axis=0)
print(newarr)

newarr = np.sum([arr1, arr2], axis=1)
print(newarr)

"""Cummulative Sum
Cummulative sum means partially adding the elements in array.
E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].
Perfom partial sum with the cumsum() function."""
newarr = np.cumsum(arr1)
print(newarr)


[2 4 6]
12
[2 4 6]
[6 6]
[1 3 6]


In [19]:
"""Products"""

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
x = np.prod(arr1)
print(x)
x = np.prod([arr1, arr2])
print(x)

#If you specify axis=1, NumPy will return the product of each array.
newarr = np.prod([arr1, arr2], axis=1)
print(newarr)

#Perfom partial sum with the cumprod() function.
newarr = np.cumprod(arr2)
print(newarr)



24
40320
[  24 1680]
[   5   30  210 1680]


In [23]:
"""A discrete difference means subtracting two successive elements.
E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]
To find the discrete difference, use the diff() function."""

arr = np.array([10, 15, 25, 5])
newarr = np.diff(arr)
print(newarr)

#We can perform this operation repeatedly by giving parameter n. E.g. for [1, 2, 3, 4], the discrete difference with n = 2 would be [2-1, 3-2, 4-3] = [1, 1, 1] , then, since n=2, we will do it once more, with the new result: [1-1, 1-1] = [0, 0]
newarr = np.diff(arr, n=3)
print(newarr)

[  5  10 -20]
[-35]


In [26]:
"""Trigonometric Functions
NumPy provides the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, cos and tan values."""

#Find sine value of PI/2:
x = np.sin(np.pi/2)
print(x)

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
print(np.sin(arr))

#Convert Degrees Into Radians
#By default all of the trigonometric functions take radians as parameters
arr = np.array([90, 180, 270, 360])
x = np.deg2rad(arr)
print(x)

#Radians to Degrees
y = np.rad2deg(x)
print(y)


#NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given (o mesmo para os hiperbólicos).
x = np.arcsin(1.0)
print(x)
arr = np.array([1, -1, 0.1])
x = np.arcsin(arr)
print(x)


#NumPy provides the hypot() function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.
base = 3
perp = 4
x = np.hypot(base, perp)
print(x)




1.0
[1.         0.8660254  0.70710678 0.58778525]
[1.57079633 3.14159265 4.71238898 6.28318531]
[ 90. 180. 270. 360.]


In [27]:
"""NumPy Set Operations"""

#We can use NumPy's unique() method to find unique elements from any array. E.g. create a set array, but remember that the set arrays should only be 1-D arrays.

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)
print(x)


#To find the unique values of two arrays, use the union1d() method.
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
newarr = np.union1d(arr1, arr2)
print(newarr)


#To find only the values that are present in both arrays, use the intersect1d() method.
newarr = np.intersect1d(arr1, arr2, assume_unique=True)
print(newarr)

#Note: the intersect1d(),setdiff1d() and setxor1d() methods take an optional argument assume_unique, which if set to True can speed up computation. It should always be set to True when dealing with sets.


#To find only the values in the first set that is NOT present in the seconds set, use the setdiff1d() method.
newarr = np.setdiff1d(arr1, arr2, assume_unique=True)
print(newarr)


#To find only the values that are NOT present in BOTH sets, use the setxor1d() method.
newarr = np.setxor1d(arr1, arr2, assume_unique=True)
print(newarr)

[1 2 3 4 5 6 7]
[1 2 3 4 5 6]
[3 4]
[1 2]
[1 2 5 6]
